nelmio_api_doc:
  documentation:
    info:
      title: Bish
      description: API du site Bish
      version: 1.0.0
    components:
      securitySchemes:
        Bearer:
          type: http
          scheme: bearer
          bearerFormat: JWT
    security:
      - Bearer: []